[GLOBAL]
pants_version = "2.20.1"
# pythonpath = ["%(buildroot)s/"]
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.docformatter",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
    "pants.backend.plugin_development",
]

[python]
enable_resolves = true
default_resolve = "pants-plugins"
interpreter_constraints = ["==3.9.*"]

[python.resolves]
pants-plugins = "lock.txt"

[python.resolves_to_interpreter_constraints]
# Pants runs with Python 3.9, so this lets us
# use different interpreter constraints when
# generating the lockfile than the rest of our project.
#
# Warning: it's still necessary to set the `interpreter_constraints`
# field on each `python_sources` and `python_tests` target in
# our plugin! This only impacts how the lockfile is generated.
pants-plugins = ["==3.9.*"]