version: 2

sources:
  - name: oci_reports
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: oci_reports
    loader: Airflow

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: oci_cost_report
      - name: oci_usage_report
