version: 2

models:
  - name: mart_crm_task
    description: "Record of all [Salesforce Tasks](https://help.salesforce.com/s/articleView?id=sf.tasks.htm&type=5) related to leads, contacts, opportunities, and accounts."
    columns:
      - name: dim_crm_task_sk
        description: '{{ doc("dim_crm_task_sk") }}'
        tests:
          - not_null
          - unique
      - name: full_comments
        meta:
           masking_policy: analyst_sales_sensitive
      - name: task_subject
        meta:
           masking_policy: analyst_sales_sensitive

  - name: mart_crm_event
    description: Record of all Salesforce Events related to leads, contact, accounts, and opportunities. 
    columns:
      - name: dim_crm_event_sk
        description: The utility-generated ID key, from the event_id. 
        tests:
          - unique
          - not_null
      - name: dim_crm_event_pk
        description: Utility-generated primary key, from the event_id
      - name: dim_crm_account_id
        description: SFDC's Account ID related to the event
      - name: dim_crm_user_id
        description: SFDC's User ID related to the event
      - name: dim_crm_person_id
        description: Utility-generated string, from the SFDC Person's ID
      - name: dim_crm_opportunity_id
        description: SFDC's Opportunity ID related to the event
      - name: sfdc_record_id
        description: SFDC's Person ID related to the event
      - name: event_date_id
        description: ID of the event_Date field
      - name: event_date
        description: Date the event took place. 
      - name: event_end_date_id
        description: ID of event's end date field. 
      - name: event_end_date
        description: Day of the end of the Event. 
      - name: reminder_date_id
        description: ID of the reminder date
      - name: reminder_date_time
        description: Date/Time that a reminder was set for this event. 
      - name: event_recurrence_end_date_id
        description: ID of the Event's recurrence end date
      - name: event_recurrence_end_date
        description: The end date of the recurrence of this event
      - name: event_recurrence_start_date_id
        description: ID of the Event's recurrence start date
      - name: event_recurrence_start_date_time
        description: The start date/time of the recurrence of this event
      - name: event_created_by_id
        description: ID of the event's creator
      - name: event_created_date_id
        description: ID of the Event's created date
      - name: event_created_date
      - name: event_id
        description: The SFDC ID for the Event. 
      - name: event_subject
        description: The Subject of the Event, from SFDC.
      - name: event_source
        description: The Event's Source, from SFDC
      - name: outreach_meeting_type
        description: The Outreach Meeting Type for the Event, from Outreach. 
      - name: event_type
        description: The Type of the Event, from SFDC
      - name: event_disposition
        description: The Disposition of the Event, from SFDC
      - name: event_description
        description: The Description of the Event, from SFDC
      - name: event_subtype
        description: The Subtype of the Event, from SFDC
      - name: booked_by_employee_number
        description: The Employee number of the Employee that booked the event/meeting. 
      - name: sa_activity_type
        description: The SA's Activity Type of the Event. 
      - name: event_show_as
        description: What the Event shows as in SFDC
      - name: assigned_to_role
        description: The SFDC Role, of the user assigned to the Event. 
      - name: csm_activity_type
        description: The CSM's Activity Type of the Event. 
      - name: customer_interaction_sentiment
        description: The Customer's sentiment/feedback on the Event
      - name: google_doc_link
        description: The link to a google doc related to the event. 
      - name: comments
        description: Comments left by the rep assigned to the event. 
      - name: qualified_convo_or_meeting
        description: Whether or not the meeting/event was a qualified conversation. 
      - name: first_opportunity_event_created_date
        description: The earliest event completion date, related to an opportunity. 
      - name: event_start_date_time
        description: The Start Date/Time of the Event. 
      - name: reminder_date_time
        description: The Date/Time of the reminder set for the Event. 
      - name: event_end_date_time
        description: The Event's End Date/Time. 
      - name: event_date
        description: The Date the Event took place. 
      - name: event_datetime
        description: The Date/Time the Event took place. 
      - name: created_at
        description: The Date the Event was created. 
      - name: event_end_date
        description: The End Date of the Event. 
      - name: is_all_day_event
        description: Boolean value - Whether or not the Event is an all day event. 
      - name: is_archived
        description: Boolean value -Whether or not the event is now archived. 
      - name: is_child_event
        description: Boolean value - Whether or not the Event is the child of another Event. 
      - name: is_group_event
        description: Boolean value - Whether or not the Event was a Group event. 
      - name: is_private_event
        description: Boolean value - Whether or not the Event was a private event. 
      - name: is_recurrence
        description: Boolean value - Whether or not the Event is  recurring Event.  
      - name: has_reminder_set
        description: Boolean value - Whether or not there is a reminder set for this Event. 
      - name: is_answered
        description: Boolean value - Whether or not the prospect/customer answered/responded to the Event invite. 
      - name: is_bad_number
        description: Boolean value - Whether or not the number dialed was a bad/faulty number. 
      - name: is_busy
        description: Boolean value - Whether or not the recipient of the call was busy. 
      - name: is_correct_contact
        description: Boolean value - Whether or not the ep reached the correct contact.  
      - name: is_left_message
        description: Boolean value - Whether or not a VM message was left. 
      - name: is_not_answered
        description: Boolean value - Whether or not the recipient did not answer the phone. 
      - name: is_meeting_canceled
        description: Boolean value - Whether or not the meeting was cancelled. 
      - name: is_closed_event
        description: Boolean value - Whether or not the Event is closed. 
      - name: is_activity
        description: Boolean value - Whether or not this Event is tracked as an activity. 
      - name: event_recurrence_activity_id
        description: ID of the Event's recurring activity. 
      - name: event_recurrence_day_of_week
        description: Day of the week for the recurrence of this event. 
      - name: event_recurrence_day_of_month
        description: Day of the month for the recurrence of this event. 
      - name: event_recurrence_end_date
        description: The End Date for the recurrence of this event. 
      - name: event_recurrence_instance
        description: Whether or not the event is recurring. 
      - name: event_recurrence_interval
        description: The interval in which the event reoccurs. 
      - name: event_recurrence_month_of_year
        description: Month of the year for the recurrence of this event. 
      - name: event_recurrence_start_date_time
        description: The Starting date/time of the recurrence of this event. 
      - name: event_recurrence_timezone_key
        description: The Timezone key for the recurrence of this event's date/time fields. 
      - name: event_recurrence_type
        description: The type of recurring Event. 
      - name: is_recurrence_2_exclusion
        description: Boolean - Whether or not the recurrence is excluded. 
      - name: is_recurrence_2
        description: Boolean - Whether or not the recurrence is valid. 
      - name: is_recurrence_2_exception
        description: Boolean - Whether or not the recurrence is an exception. 
      - name: last_modified_id
        description: The ID of the last modifier of this event. 
      - name: last_modified_date
        description: The Date the event was last modified. 
      - name: systemmodstamp
        description: The time/date stamp from SFDC when this record was created. 

  - name: rpt_scaffold_sales_funnel
    description: Scaffold table that provides a foundational structure between fct_sales_funnel_actual and fct_sales_funnel_target_daily to support the visualization layer. Link to handbook documentation on [scaffold tables](https://about.gitlab.com/handbook/business-technology/data-team/platform/edw/#scaffold-tables)
    columns:
      - name: CONCAT(date_id, dim_sales_funnel_kpi_sk, dim_hierarchy_sk, dim_order_type_id, dim_sales_qualified_source_id)
        tests:
          - not_null
          - unique
