version: 2
models:
  - name: rally_initial_export_optouts_source
    description: Data from Rally application indicating if user is optin or not
    columns:
      - name: email
        tests:
          - not_null
      - name: opted_out
      - name: updated_at
        tests:
          - not_null
