version: 2
 
sources:
 - name: iterable
   database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
   schema: iterable
   loaded_at_field: _fivetran_synced
   loader: fivetran
   description: Iterable data
 
   quoting:
     database: true
     schema: false
     identifier: false
 
   tables:
     - name: user_history
     - name: user_unsubscribed_channel
     - name: user_unsubscribed_message_type