name: Pull Request CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  get_ci_lockfiles:
    name: Get Pants CI Versions
    runs-on: ubuntu-latest
    outputs:
      ci_lockfiles: ${{ steps.get-ci-lockfiles.outputs.CI_LOCKFILES }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Get Pants Versions
        id: get-ci-lockfiles
        run: |
          echo "CI_LOCKFILES<<EOF" >> $GITHUB_OUTPUT
          ls ci-lockfiles | 
            jq -R --slurp 'rtrimstr("\n") | split("\n") | map({"lockfile": (.), "version": (. | ltrimstr("release_") | rtrimstr(".lock"))})' | 
            tee -a $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  run_ci:
    name: "Continuous Integration"
    runs-on: ubuntu-latest
    needs: [get_ci_lockfiles]
    strategy:
      matrix:
        pants_version_lockfile: ${{ fromJson(needs.get_ci_lockfiles.outputs.ci_lockfiles) }}
        # os:
        #   - ubuntu-latest
        #   - macos-latest
    env:
      PANTS_VERSION: ${{ matrix.pants_version_lockfile.version }}
      PANTS_PYTHON_RESOLVES: "{\"pants-plugins\": \"ci-lockfiles/${{ matrix.pants_version_lockfile.lockfile }}\"}"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Python(s)
        uses: actions/setup-python@v5
        with:
          python-version: |
              3.8
              3.9
              3.10
              3.11
      - name: Initialize Pants
        uses: pantsbuild/actions/init-pants@main
        with:
          gha-cache-key: cache0-pants${{ matrix.pants_version_lockfile.lockfile }}
          named-caches-hash: ${{ hashFiles(matrix.pants_version_lockfile.lockfile) }}
      - name: Lint
        run: |
          pants tailor --check update-build-files --check lint ::
      - name: Typecheck
        run: |
          pants check ::
      - name: Test
        run: |
          pants test ::
